user exception caught
error call caught
no method error
exceptionsrun001.hs:39:1-13: Non-exhaustive patterns in function test1
exceptionsrun001.hs:46:1-26: Non-exhaustive patterns in function test2
